### ISSUE TITLE
Unable to run the client application 

### ISSUE THREAD

**Issue by shahriarhossain** [ch-mubarak/DAG-path-generator#1]
I was trying to run your client application, unfortunately when I have tried to install packages, I got the following error:
![image](https://user-images.githubusercontent.com/6463320/212647294-e9ce094d-502f-4c4d-9777-fea4e8ae89a9.png)

Can you please guide how did you manage to avoid this issue.

**Comment by ch-mubarak** [comment]
react and d3 are [peer-dependencies](https://nodejs.org/en/blog/npm/peer-dependencies/), this means that the responsibility to install them is delegated to the client. This will give you more flexibility on what versions of d3 and react you want to consume, you just need to make sure that you are compliant with the range of versions that react-d3-graph is compatible with. If you install react-d3-graph without first installing d3 and react you might see the warnings:

or you can just use 

> npm i --force

. will work fine (make sure you installing `d3@^5.5.0 ` not the latest version. other wise you will face some bugs when dragging nodes )
